name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-frontend-lib-generic.yml@640270ba31c66137344548fc62379fdf1dd7e490
    with:
      eventType: diagram_viewer_updated
      licensercPath: .github/config/.licenserc.yaml
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
